[package]
name = "rooms-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
axum_responses = "0.4.6"
lazy_static = "1.5.0"
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
